### ISSUE TITLE
ImportError: cannot import name '_input_format_classification' from 'pytorch_lightning.metrics.utils'

### ISSUE THREAD

**Issue by WZheyi** [tobiascz/TeCNO#4]
when I run the command 
_python train.py -c modules/mstcn/config/config_tcn.yml_

there is a error in  "/TeCNO/modules/mstcn/tecno.py":
the version of pytorch_lightning==1.0.6 has no the class name "_input_format_classification".

Can someone tell me the correct version of pytorch_lightning?

**Comment by tobiascz** [comment]
Using the master should work. I already updated the requirements. 
Cheers

**Comment by MeganClark-Robinson** [comment]
Hi. I have the same issue.
