### ISSUE TITLE
prepare cholec_split_250px_25fps.pkl 

### ISSUE THREAD

**Issue by kingofapplehead** [tobiascz/TeCNO#5]
Hi,

Thanks for sharing the code of your wonderful work.

I followed the instructions and was trying to train the feature extractor as the first step. I've read the code, and my understanding of cholec_split_250px_25fps.pkl is that it's a pickled file including"image_path", "phase class", "time", "video","tool_Grasper", "tool_Bipolar", "tool_Hook", "tool_Scissors", "tool_Clipper", "tool_Irrigator", "tool_SpecimenBag" as the columns. 

I wonder where does the "index_nan = [1983913, 900090]" in TeCNO/datasets/cholec80_feature_extract.py come from? Why 1983913, 900090?

Since the cholec_split_250px_25fps.pkl is prepared with 25fps and tool annotations are only given at 1fps. Wouldn't the tool columns for the images with unavailable tool annotation be all nan? 

Please excuse me if my questions are too naive.. I am new to this. Thanks a lot for your help.

**Comment by tobiascz** [comment]
these NAN indexes come from the fact that I create 2 additional frames with my version of ffmpeg. So from 2 videos the labels have x amount of rows and these 2 additional frames dont have a corresponding label. It would be cleaner to assign them to the last class but for practicality reasons I just drop 2 frames (out of 4.5 mio frames).
The tool information get interpolated so each tool info creates 25 rows in the final data frame.

**Comment by Fan2022HNU** [comment]
Thanks for sharing the code of your wonderful work.  I've made a mistake here。
"No such file or directory: 'xxx/dataframes/cholec_split_250px_25fps.pkl'", I can't find the file "cholec_split_250px_25fps.pkl".
