### ISSUE TITLE
what are the model settings to reproduce your best results?

### ISSUE THREAD

**Issue by wenxixi** [tobiascz/TeCNO#6]
Hi, I wonder what the model settings are in order to reproduce your acc=88.56±0.27 prec=81.64±0.41 rec=85.24±1.06 results? 

While the paper states that num_stages=2, what did you use for num_features, and num_layers? Could you please confirm if they are 32 and 8? 

The config file and the comments in code don't seem consistent. And I did find it in your paper. Thanks.

![image](https://user-images.githubusercontent.com/42296651/111574879-42ee2d80-87e8-11eb-9a2b-6a1557bf5e1a.png)

![image](https://user-images.githubusercontent.com/42296651/111574951-674a0a00-87e8-11eb-849f-6b5c5f450c6f.png)

**Comment by tobiascz** [comment]
for the best performing TeCNO model I used:
mstcn_layers: 9 
mstcn_f_maps: 64
mstcn_f_dim: 2048
mstcn_stages: 2
