### ISSUE TITLE
is it possible to share your trained multi-head resnet 50 model?

### ISSUE THREAD

**Issue by wenxixi** [tobiascz/TeCNO#7]
Dear authors, 

Thanks for sharing the great work. 

I would like to ask whether you would kindly consider sharing your trained multi-head resnet50 model on cholec80?

Thank you.

**Comment by wenxixi** [comment]
Also, would it be possible that you share the input features? (the input features that you got from the trained 2-headed resnet which you directly put into mstcn)

**Comment by tobiascz** [comment]
I will try to provide this checkpoints but unfortunately the size of the feature files are too big to be shared online
