### ISSUE TITLE
cholec_split_250px_25fps.pkl not found error

### ISSUE THREAD

**Issue by MeganClark-Robinson** [tobiascz/TeCNO#8]
Hi.

Thank you so much for sharing your perfect code. When I try to run the code, it gives a FileNotFoundError:

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/polyaxon/data1/cholec80/dataframes/cholec_split_250px_25fps.pkl'

where can I find this file? cholec_split_250px_25fps.pkl

Thank you so much and best wishes.

**Comment by tobiascz** [comment]
Hi Megan,

You have to create this file using the splitted videos:
https://github.com/tobiascz/TeCNO/blob/master/utils/tecno/create_dataframe.py
