### ISSUE TITLE
ImportError: cannot import name '_input_format_classification' from 'pytorch_lightning.metrics.utils'

### ISSUE THREAD

**Issue by MeganClark-Robinson** [tobiascz/TeCNO#9]
Hi. When I run:

python train.py -c modules/mstcn/config/config_tcn.yml

it gives this error. I installed the requirements file and even using
pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master

it gives this error. Thanks.

**Comment by tobiascz** [comment]
What error does it give? I should have fixed the versions of the requirements in the file. I think I accidentally removed them. In the new requirements file i added the versions please try it again with the correct library version.

**Comment by tobiascz** [comment]
https://github.com/tobiascz/TeCNO/blob/master/requirements.txt
